engines:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 130
    exclude_paths:
    - "test/"
  eslint:
    enabled: true
    channel: "eslint-3"
  fixme:
    enabled: true
